# Generated by Django 5.1 on 2024-08-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berdanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
